// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMyVzYUOjaLhYN7-_7JPnFt3KGi7KvKQY',
    appId: '1:768123001909:web:beee8589d8d47781b3257c',
    messagingSenderId: '768123001909',
    projectId: 'cart-58cbe',
    authDomain: 'cart-58cbe.firebaseapp.com',
    storageBucket: 'cart-58cbe.firebasestorage.app',
    measurementId: 'G-JVMB70WWRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARWfScsaAgwafPSGKAOUSRL84PedwQZCQ',
    appId: '1:768123001909:android:53bb463fab5f21f2b3257c',
    messagingSenderId: '768123001909',
    projectId: 'cart-58cbe',
    storageBucket: 'cart-58cbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC1-LoGszsKfJh63mseiVYg1cIoDCtuoo',
    appId: '1:768123001909:ios:9ae92affb8cdcb99b3257c',
    messagingSenderId: '768123001909',
    projectId: 'cart-58cbe',
    storageBucket: 'cart-58cbe.firebasestorage.app',
    iosBundleId: 'com.example.cart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC1-LoGszsKfJh63mseiVYg1cIoDCtuoo',
    appId: '1:768123001909:ios:9ae92affb8cdcb99b3257c',
    messagingSenderId: '768123001909',
    projectId: 'cart-58cbe',
    storageBucket: 'cart-58cbe.firebasestorage.app',
    iosBundleId: 'com.example.cart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMyVzYUOjaLhYN7-_7JPnFt3KGi7KvKQY',
    appId: '1:768123001909:web:48239a47a091a430b3257c',
    messagingSenderId: '768123001909',
    projectId: 'cart-58cbe',
    authDomain: 'cart-58cbe.firebaseapp.com',
    storageBucket: 'cart-58cbe.firebasestorage.app',
    measurementId: 'G-7C6PJ2K2F7',
  );
}
